symbols:
  # The SEVEN
  - ['TSLA',  'NASDAQ']
  - ['NVDA',  'NASDAQ']
  - ['AAPL',  'NASDAQ']
  - ['AMZN',  'NASDAQ']
  - ['GOOGL', 'NASDAQ']
  - ['META',  'NASDAQ']
  - ['MSFT',  'NASDAQ']
  
  - ['AVGO',  'NASDAQ']
  # - ['PLTR',  'NASDAQ']
  - ['IBKR',  'NASDAQ']
  # - ['VST',  'NASDAQ']

  # - ['QQQ',   'NASDAQ']
  # - ['SOXL',  'ARCA']

redis:
  host: "localhost"
  port: 6379
  password: verysecret
  db: 0
