version: "3.8"

services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    environment:
      - REDIS_PASSWORD=verysecret
    command: ["redis-server", "--requirepass", "verysecret"]
    restart: always

  # backtest:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: backtest_service
  #   runtime: nvidia
  #   environment:
  #     - NVIDIA_VISIBLE_DEVICES=all
  #   volumes:
  #     - .:/workspace
  #   command: ["/usr/bin/tail", "-f", "/dev/null"]
  #   working_dir: /workspace
